FROM python:3.13-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY ./app ./src

COPY ./docker/entrypoint.sh ./

RUN chmod +x entrypoint.sh

ENTRYPOINT [ "/bin/sh", "/app/entrypoint.sh" ]
